# Welcome to Jekyll!

# Website settings
title: "Mutouboy"
description: "Mutouboy`s blog"
keywords: "Mutouboy,蒋文斌，中国计量大学"
baseurl: "/"
url: "http://www.jwb5.cn"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Mutouboy'
  first_name: ''
  last_name: '蒋文斌'
  email: 'jwb@jwb5.cn'
  # facebook_username: 'jiakunnj'
  github_username: 'Mutouboy'
  avatar: 'static/img/landing/my.jpg'
  desc: 'Java开发工程师，硕士，2019年6月毕业于中国计量大学计算机应用技术专业'


# share
bshare:
  uuid: 1efa96de-7019-44ca-814e-70f5da7c54f8

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-90086842-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
